---
title: Recommendations for reporting epidemiological parameters
author:
  - name: Joshua W. Lambert
    orcid: 0000-0001-5218-3046
    corresponding: true
    email: joshua.lambert@lshtm.ac.uk
    affiliations:
      - London School of Hygiene and Tropical Medicine
  - name: Carmen Tamayo
    orcid: 0000-0003-4184-2864
    corresponding: false
    email: carmen.tamayo-cuartero@lshtm.ac.uk
    affiliations:
      - London School of Hygiene and Tropical Medicine
  - name: Sangeeta Bhatia
    orcid: 0000-0001-6525-101X
    corresponding: false
    email: s.bhatia@imperial.ac.uk
    affiliations:
      - Imperial College London
      - UK Health Security Agency
  - name: Ruth McCabe
    orcid: 0000-0002-6368-9103
    corresponding: false
    email: ruth.mccabe17@imperial.ac.uk
    affiliations:
      - Imperial College London
  - name: Gina Cuomo-Dannenburg
    orcid: 0000-0001-6821-0352
    corresponding: false
    email: g.cuomo-dannenburg18@imperial.ac.uk
    affiliations:
      - Imperial College London
  - name: Adam Kucharski
    orcid: 0000-0001-8814-9421
    corresponding: false
    email: adam.kucharski@lshtm.ac.uk
    affiliations:
      - London School of Hygiene and Tropical Medicine
  - name: Anne Cori
    orcid: 0000-0002-8443-9162
    corresponding: false
    email: a.cori@imperial.ac.uk
    affiliations:
      - Imperial College London
keywords: 
  - epidemiological parameters
  - reporting guidelines
date: last-modified
bibliography: references.bib
---

{{< include paper/abstract.qmd >}}

## Introduction

Epidemiological parameters are quantities that characterise the spread of infectious diseases, their epidemiological outcomes and temporal information on dynamics of disease progression and transmission [@coriInferenceEpidemicDynamics2024]. They are critical to understand epidemic and pandemic dynamics and respond accordingly [@polonskyOutbreakAnalyticsDeveloping2019]. Most epidemiological parameters take the form of distributions because there is inherent variability in the epidemiological characteristics being measured. An illustration is the delay from infection to symptom onset. The variability of individuals in immune response and variability of the infectious agent in pathology are two ways, among many others, that lead to some individuals having shorter time delay between infection and onset of symptoms. Due to most epidemiological parameters being described by distributional forms they are estimated by fitting distributions to epidemiological data on cases or contacts.

It has become general practice that when epidemiological parameters are required, either for analyses of epidemiological case data or to make policy decisions like quarantine duration, that the literature is searched to find a suitable peer-reviewed publication reporting the parameter needed. However, this process has several limitations. The time requirement to search through papers to find the highest quality epidemiological parameter means that in time-limited scenarios, for example early in an outbreak when the situation is evolving rapidly and new data is continually gathered, a suboptimal parameter set may be extracted and used. This has lead to previous _ad hoc_ reviews of epidemiological parameters for specific pathogens (e.g. Ebola [@vankerkhoveReviewEpidemiologicalParameters2015a]). The choice of parameter is also likely to be somewhat subjective without a clear quality assurance framework to evaluate and compare different parameter estimates. The manual extraction of copying and pasting parameters out of the literature comes with the risk of discrepancies entering the calculations.

Epidemiological parameters have been reported for many diseases and the data used to infer parameter estimates and the methods of inference vary.

Efforts to compile a centralised database of epidemiological parameters have highlighted the variability and ambiguity in parameter reporting which can lead to uncertainty around what is being reported and how these epidemiological parameters can be applied in other epidemiological analyses [@cuomo-dannenburgMarburgVirusDisease2024; @doohanLassaFeverOutbreaks2024; @nashEbolaVirusDisease2024].

This paper was motivated by several research groups independently attempting to compile a comprehensive library of epidemiological parameters which could serve as a public resource to easily search, filter and extract parameters. These groups gathered for a workshop convened by the World Health Organisation (WHO) Collaboratory in Spring 2024, in which a Global Repository of Epidemiological Parameters (GREP) was discussed, as well as ideas for guidance on reporting epidemiological parameters. The guidelines and examples of incorrect reporting and use were subsequently further developed and resulted in this paper.

Our focus is on guidance for reporting epidemiological parameters from a variety of study types and estimation methodologies. We do not cover or advice on best practises for parameter estimation methods. There are several papers that address avoiding biases and pitfalls [@kingAvoidableErrorsModelling2015; brittonEstimationEmergingEpidemics2019a]. Specificall for guidance on methodologies when inferring delay distributions see @parkEstimatingEpidemiologicalDelay2024 and @charnigaBestPracticesEstimating2024, and when inferring the reproduction number see @gosticPracticalConsiderationsMeasuring2020a and abbottEstimatingTimevaryingReproduction2020. We focus on the reporting of epidemiological parameters post-inference and the benefits of reporting standardisation on the reuse of parameters by those involved in epidemic or humanitarian response.

We classify bad parameter reporting into two groups: 1) _information loss_ and 2) _ambiguous reporting_. Information loss is defined as the presentation or sharing of less than the entirety of the parameter estimates, metadata and contextual information. For example, if a method to infer a case fatality rate outputs the uncertainty of the risk but this is not reported either in the text and the method cannot be reproduced then this information is lost when others extract the parameters, i.e. only a subset of the full inference is shared. Ambiguous reporting can be either the ambiguous reporting of metrics, such as a $X \pm Y$ where $Y$ could be the standard deviation or standard error, or $X (Y_1 - Y_2)$ where the bounds $Y_1$ and $Y_2$ could be a confidence interval or credible interval when the inference framework is not reported. In both cases the secondary use of the parameters either is forced to make an assumption on what is reported, or does not utilise the information resulting in information loss.

Here we focus on the bias caused by badly reported epidemiological parameters on simple epidemic methods, sometimes referred to as outbreak analytics [sensu @polonskyOutbreakAnalyticsDeveloping2019], to showcase the erroneous conclusions that can arise when using parameter estimates from the literature. The biases produce here will likely extrapolate to more complex epidemiologilogical modelling. Reporting guidelines can ensure standardised reporting becomes more commonplace, which can make it easier to review, summarise and aggregate epidemiological parameters. We hope that this paper, alongside other works on reporting best practises in epidemiology [@pollettRecommendedReportingItems2021; @charnigaBestPracticesEstimating2024] enhance the interoperability of research outputs and inputs.

## Guidance

### Parameter inference reporting

#### Parameterisation of distributions

Many distributions have standard parameterisations. In other words, they have one, two or in some cases three parameters that are denoted by a name and often have a greek letter for shorthand. An example of this is the Gamma distribution which has the parameterisation shape ($\alpha$) and rate ($\beta$). However, there are often alternative parameterisations, for the Gamma distribution this is shape ($k$) and scale ($\theta$). If left unspecified, the reported parameters may correspond to different parameters depending on interpretation. Another example of ambiguous reporting of distribution estimates is when the parameters and summary statistics have similar names. This is the case for the lognormal distribution, whose common parameterisation is meanlog ($\mu$) and sdlog ($\sigma$) and common summary statistics reported for a distribution are mean and standard deviation (sd), this is further confused as both use the same greek letters. Therefore, it is possible to mistake the reporting of one set of these for the other. Both types of misinterpretation outlined here can result in substantial differences in the distributions (Figure 1).

::: {.callout-note title="_Guidance_"}
* Provide the formula for the Probability Density Function (PDF), or Probability Mass Function (PMF) if discrete, in the text or supplementary material.
* Clearly report which distribution parameterisation was used to estimate parameters and provide parameter names in the text. 
* Share code used to estimate parameter(s) for others to reproduce and audit methods.
:::


{{< embed use_cases/dist_params.qmd#fig-dist-params >}}

#### Parameter estimates vs summary statistics

Instead of reporting the parameter estimates for a parametric distribution, summary statistics may be provided. In some instances a set of summary statistics can be analytically converted into distribution parameters (the specific summary statistics that can be converted into parameters varies by distribution). In those cases where analytical conversion can be done there is no loss in parameter estimate precision, i.e. summary statistics are sufficient statistics. Commonly reported sufficient statistics are the mean and standard deviation or variance of a distribution. However, it can also be the case that summary statistics that cannot be analytically converted to distribution parameters are reported, for example the mean or median and the 95th percentiles of the distribution. In these cases, distribution parameters require a second estimation using a numerical conversion. Numerical conversion can introduce more uncertainty and potentially return erroneous estimates. Below we show an example of the bias and variance of distribution parameters when numerically converted from summary statistics… (see {epiparameter} R package article for full exploration of bias in numerical conversion).

Epidemiological parameters can be dimensionless quantities, for example R0 or secondary attack rate, while others have units. It is especially critical for the accurate reuse of with dimensions parameters that the units are reported. For parameters with a temporal dimension, such as delay distributions, the unit of time ensures that distributions fitted to data on days or weeks can be clearly understood. Another example is viral load data that can be reported as Ct or log10 RNA copies/ml. Many epidemiological parameters will have conventional units, for example incubation period and serial interval in days, or population density in individuals/km, but if readers have to assume units then misinterpretation can have consequences for others that apply the findings in their own work.

_Guidance_:

* Report the estimated distribution parameters first and foremost before optionally reporting summary statistics. This will avoid any secondary estimation step which can introduce unwanted and unnecessary bias. 
* If a parameter has a unit, report this with the estimates, ensuring it matches the data of input of the model.

::: {.callout-tip}
## Use case: Severity
{{< include use_cases/cfr_dist_params.qmd >}}
:::

#### Parameter uncertainty vs sample variability

The reporting of distributions is to encapsulate the variability of epidemiological delays, transmission, severity and others. However, there is also uncertainty around the parameters estimated. If it is not clearly stated that a distribution was fit to the data, it can be unclear whether the uncertainty around the mean corresponds to variation in the epidemiological case data, i.e. differences between individuals resulting in a distribution, or to the confidence or credible interval around the estimated mean. 

#### Reporting inference method

The inference method used to infer epidemiological parameters and the uncertainty that is coupled with those estimates is also important to report precisely for it to be used in downstream analyses. One common distinction that can be made between inference method is whether it uses Maximum likelihood estimation (MLE) or Bayesian estimation. The resulting uncertainty of parameters, confidence intervals (CI) for MLE and credible intervals (CrI) for Bayesian fitting, cannot be interpreted or applied interchangeably [@moreyFallacyPlacingConfidence2016]. Therefore if wanting to propagate uncertainty in parameter estimates, incorrectly treating CI as CrI or vice versa will lead to bias.

Reporting on Bayesian fitting also has several summary statistics to describe the central tendency of the inferred posterior sample, for example, mean, median, mode. It is beneficial for the specific central tendency statistic used to be explicitly stated.

_Guidance_:

* Report distribution parameters with uncertainty if available. This can be reporting the confidence interval (CI) or credible interval (CrI) making it clear 
* When using Bayesian inference, specifying methods used for posterior distribution and making posterior sample openly available via data sharing platform, e.g., Zenodo, Data Dryad.

The types of distributions commonly fit to estimate delay distributions, such as serial interval, onset-to-event and incubation period, are Gamma, lognormal and Weibull. These are used as they are strictly positive (sometimes offsets or other distributions are used to account for negative serial intervals (Prete Jr. et al., 2021)) and are right-skewed, meaning that most of the distribution mass (i.e. area under the curve) is the left of the mean (Figure 1). It is best practice to fit multiple distributions to the data and compare models using likelihoods, information criteria or likelihood ratio tests. By reporting these comparisons with each set of estimated parameters it allows others to use the distribution they choose while also being aware of the goodness-of-fit if choosing the non-best-fitting distribution. 

_Guidance_: 

* If multiple distributions are fit to the raw case data, report the goodness-of-fit (e.g. maximum likelihood, Akaike Information Criterion) and the parameter estimates of each distribution either in the main text or in the supplementary material. 

### Contextual information and metadata

Since pathogen transmission and spread is known to be affected by socioeconomic, demographic, and climatic factors, reporting relevant contextual information alongside parameter estimates is crucial to understand the circumstances in which these estimates were obtained. Doing so will allow external readers to make informed decisions about the generalisability of the reported parameters and usability in their own analyses. 

An important contextual element is detailed information about the sample population from which parameters were estimated, including factors such as the geographic location, age distribution, and comorbidities. This is particularly relevant in those studies where only a specific subset of the population was sampled, such as health-care workers, pregnant individuals, or immunocompromised patients. 

Other relevant details of the study, such as the type of design and sampling strategy, should not be overlooked, when reporting epidemiological parameters, as these provide relevant contextual information to assess the representativeness of the data and validity of the statistical methods applied. For instance, methods for estimating parameters like the serial interval require considering data collection methods, as different adjustments for biases are needed depending on whether data on transmission pairs was conducted prospectively or retrospectively (see section 1.5). The specific case definition used to estimate parameters should also be reported, where possible, given the range of clinical signs that many diseases exhibit at different stages of infection, which can have an impact on the estimation of parameters like the incubation period or delays from onset to outcome.

Where parameters are reported or inferred during an active outbreak, we recommend to provide information about the time into the outbreak since the first case was reported and epidemic phase at the time of the analysis, especially when inferring delay distributions (see section 1.5). Further contextual information is also relevant for a nuanced understanding of how parameter estimates may change throughout an outbreak, e.g., due to changes in containment measures, therapeutics and vaccination, or volume of testing. For instance, advancements in the therapeutic approach to critical care patients resulted in a significantly higher delay from onset to death for COVID-19 patients during the summer of 2020 (mean of 24.7 days), compared to the first wave of the pandemic (mean of 19.6 days) (Ward and Johnsen, 2021, PLoS).

Contextual information about the disease’s causative agent should also be reported, including pathogen name, and, where applicable, its type, subtype and/or strain. This information is relevant, as the transmissibility, pathogenicity and severity of disease, and their resulting epidemiological parameters often vary across strains of the same pathogen. For instance, the incubation period for Influenza type A is reportedly longer on average than that of Influenza type B, with a median of 1.4 and 0.6 days, respectively (Lessler, 2009).  If the causative agent is unknown to the authors, either due to it being a novel pathogen, or simply because this information is not available, this should be explicitly stated in the publication. Beyond details about the causative agent, authors should also specify the transmission routes that have been considered when estimating parameters. This is particularly crucial for zoonotic and vector-borne diseases, where explicit clarification is needed on whether the estimates account for human-to-human transmission only, or if animal-to-human or vector-to-human transmission is also accounted for. 

_Guidance_:

* Provide demographic information about the population and for the sample that was used to estimate epidemiological parameters.
* Specify whether analyses were stratified by certain groups, e.g., by age, or conducted using data for the whole population.
* Indicate whether reported parameters were obtained during an ongoing outbreak and, if so, provide information on the epidemic phase and time since outbreak was first declared.
* Clearly state whether variant(s) of the pathogen of interest is known and, if so, report the name of the variant and how this was determined.
* Specify which transmission pathways of disease were considered, e.g., human-to-human only, or including animal-to-human transmission.

### Open science and reproducibility to enhance reuse

The complexities involved in estimating and reporting epidemiological parameters mean that it is unlikely that all methodological aspects and considerations can be documented in the paper or even supplementary material. By sharing data and code it enables reproducibility and auditing of the methods used. Sharing the code used to infer an epidemiological parameter enables others to see which method, as well as any other packages that were used. There are several platforms that easily enable code sharing, most common are GitHub, GitLab and BitBucket. To release the software used and provide a unique identifier (e.g. DOI) services like Zenodo, Figshare and Dyrad, this provides a single referenceable snapshot of the code, removing any issue if the code changes on, for example GitHub. Following these and other good practices for code sharing will help others navigate and review the code (Wilson et al., 2017). Openly sharing code enables others to reproduce the estimates and verify the estimates. They may also be able to assess the quality of the methods with respect to the available data and possible bias-adjustments that may be required when working with real-time outbreak data (citation needed). Sharing the analysis code can also resolve ambiguities in parameter reporting. If the parameterisation of the distribution is unclear from the text (see Section 1) then by checking parameter arguments in the code clarifies their use.

Sharing the data is as important as sharing the code. By data we mean the input data (i.e. outbreak case data) and output data (i.e. parameter estimates and fitting metadata). If possible the raw data used to fit a model to estimate an epidemiological parameter should be openly available. By sharing the raw data it enables reproducibility of the analysis used to estimate the epidemiological parameters, but also allows others to apply different models to the data. 

Openly sharing epidemiological data can be restricted by personal identifiable information (PII) and data usage restrictions. There are some methods available to enable reproducibility even when the raw data cannot be shared. Anonymisation, if the personal identifiable information (PII) is not required by the method to infer the epidemiological parameter then this information can be removed, de-identified or anonymised prior to uploading the data (citations needed). Mock or synthetic data can be generated which has the same characteristics as the empirical data. This enables the analysis to be reproduced while removing any risk of identification or leaking personal information. 

The epidemiological parameter output should also be shared in full when possible. Often if the epidemiological parameter are distribution parameters these will be reported in the text. But the estimates correlation matrix, variance-covariance matrix, convergence metrics (e.g. …) should be shared. For Bayesian analyses sharing the posterior distribution is most beneficial for reuse as it allows researchers to calculate whichever summary metric their use case requires (e.g. Highest Posterior Density (HPD) Interval).


### Epidemiological parameter use and disjoint analysis pipelines

The aim of this paper has been to provide a set of reporting guidelines for epidemiological parameter, with the objective to make reusing them in other epidemiological analyses more reliable, with examples showcasing when analysis error can result from erroneous or ambiguous reporting. This argument is premised on the downstream epidemiological analysis being disjoint from the estimation of the epidemiological parameters, in other words the method that uses the parameters to estimate or infer another aspect of an outbreak does not estimate the parameters. An example of this is when an previously estimated generation time, or serial interval as a more commonly available replacement, is used to estimate the real-time reproduction number. If the data is available to jointly estimate the generation time or serial interval with the reproduction number, then this is the statistically optimal approach. However, for a variety of reasons, primarily model complexity of joint models leading to mathematical and computations simplification being required, the disjoint or 2-step analysis procedure is common (ref). Some models to offer joint estimation given sufficient data (ref). There have not been many studies exploring the statistical performance of joint versus disjoint estimation (check this sentence and find ref). There is another aspect to consider, whether a set of epidemiological parameters exists where the features of the data (e.g. sample size, collection procedure) make it more accurate than the available at hand. In this scenario even if a joint estimation framework is available and feasible, it might be better to choose estimated parameters. The contextual information of the data, such as demography, geography, and comorbidities of the sample, should also be considered in such a case as the two groups might not be epidemiologically equivalent.  That is all to say that reporting guidelines are relevant due to the widespread use of disjoint estimation where clear, ambiguous reporting with coverage of key piece of statistical and contextual information are required.

## Conclusion

## References
